version: '2'
services:
    topcommerce-app:
        image: topcommerce
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://topcommerce-mysql:3306/topcommerce?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    topcommerce-mysql:
        extends:
            file: mysql.yml
            service: topcommerce-mysql
